### ISSUE TITLE
Frontend issues

### ISSUE THREAD

**Issue by danr** [NBISweden/encam#97]
Moving some small issues to this one.

Todo:
- [x] Link color in markdown content in the `Main` component
- [x] Add reference to markdown
- [ ] GroupForm: bring back stitch (was #65)
- [x] Manual check for issues in different browsers
    - [ ] Textarea edit in admin interface did not work when Artur tried (was #102)
- [x] Fix axis label position here:
![image](https://user-images.githubusercontent.com/199380/105736730-65c13b80-5f35-11eb-869e-5613be71275d.png)
- [ ] Overflow-y on boxpylots have no effect here since fom&plot overflows parent:
![image](https://user-images.githubusercontent.com/199380/104692337-19d9ef80-5708-11eb-91b1-b025570757b3.png)

Maybe:
- [ ] Tests for KMPlotWithControls, in particular the `next` function (was #75)
- [x] Polyfills for IE 11: flat and flatMap, https://github.com/es-shims/Array.prototype.flatMap (was #74)
- [ ] KMPlot: Use Tooltip? The KMPlot has the tooltip off. Do we want to show any contents in it? (was #66)

Done:
- [x] Explicit px in css (was #93)
- [x] Layout messed up here. Problem with upgrading material-ui? 
![image](https://user-images.githubusercontent.com/199380/98728547-f27a4580-2399-11eb-877b-29b6108ce89a.png)
- [x] Legend broken. Problem with vega-lite being upgraded?
![image](https://user-images.githubusercontent.com/199380/98728662-15a4f500-239a-11eb-9bb9-62101ff36cf5.png)

**Comment by danr** [comment]
Overflow-y on boxpylots have no effect here since fom&plot overflows parent:
![image](https://user-images.githubusercontent.com/199380/104692337-19d9ef80-5708-11eb-91b1-b025570757b3.png)

**Comment by danr** [comment]
![image](https://user-images.githubusercontent.com/199380/105736730-65c13b80-5f35-11eb-869e-5613be71275d.png)
No idea what has happened with axis label position here...

**Comment by danr** [comment]
* [x] Middle section should grow to make full height here
![image](https://user-images.githubusercontent.com/199380/106258784-98618180-621e-11eb-863d-257d77aa3ffe.png)

**Comment by danr** [comment]
* [x] Add some error message on `<script nomodule>...`

**Comment by danr** [comment]
Closing because all critical points are addressed
